//DIANA PADILLA ZAMORA
//REALIZA UN ALGORITMO QUE CALCULE LA EDAD DE UNA PERSONA
Proceso ALGORITMO_EDAD
	
	ESCRIBIR "BIENVENIDO AL PROGRAMA DE CALCULO DE EDAD";
	
	DEFINIR NACIMIENTO, FACTUAL, EDAD COMO ENTEROS;
	ESCRIBIR "POR FAVOR INGRESE EL AÑO ACTUAL";
	LEER FACTUAL; 
	ESCRIBIR "POR FAVOR INGRESE EL AÑO DE NACIMIENTO"; 
	LEER NACIMIENTO; 
	EDAD<-FACTUAL-NACIMIENTO;
	ESCRIBIR "SU EDAD ES:", EDAD; 
	
FinProceso
