//DIANA PADILLA ZAMORA
//DADA LA CANTIDAD EN PESOS, OBTENER LA EQUIVALENCIA EN DOLARES, 
//ASUMIENDO QUE LA UNIDAD CAMBIARÍA ES UN DATO DESCONOCIDO

Proceso DOLARES_TASA
	
	DEFINIR PESOS, TASA, TOTAL COMO REAL;
	
	ESCRIBIR "PROGRAMA DE CALCULO DE TASA CAMBIARIA";
	ESCRIBIR "INGRESA LA CANTIDAD DE PESOS";
	LEER PESOS;
	ESCRIBIR "INGRESA LA TASA DEL DÍA DE HOY";
	LEER TASA; 
	TOTAL<-PESOS/TASA;
	ESCRIBIR "TOTAL: $", TOTAL;
	
FinProceso
