
Proceso PASSWORD_NUMERICA
	//CREA UN PROGRAMA QUE LE PIDA AL USUARIO SU CONTRASEÑA (NUMERICA). 
	//DEBERA TERMINAR CUANDO INTRODUZCA COMO CONTRASEÑA EL NUMERO 4567
	//PERO VOLVERA A PEDIR TANTAS VECES COMO SEA NECESARIO 
	DEFINIR CONTRA COMO REAL; 
	CONTRA<-1;
	
	MIENTRAS CONTRA<4567 HACER
		ESCRIBIR "INGRESA TU CONTRASEÑA POR FAVOR";
		LEER CONTRA;
	FinMientras
	
FinProceso
