Proceso IMPRESION_NUMERICA
	//CREA UN PROGRAMA QUE ESCRIBA EN PANTALLA LOS NUMEROS DEL 1 AL 10
	
	ESCRIBIR "BIENVENIDO AL PROGRAMA DE IMPRESION NUMERICA"; 
	DEFINIR X COMO ENTERO; 
	X<-1;
	MIENTRAS X <= 10 Hacer
		ESCRIBIR X;
		X<-X+1;
	FinMientras
	
FinProceso
