Proceso NUMEROS_DESCENDENTES
	//CREA UN PROGRAMA QUE ESCRIBA EN PANTALLA LOS NUMEROS PARES DEL 60
	//AL 10 DESCENDENTE
	
	ESCRIBIR "BIENVENIDO AL PROGRAMA DE IMPRESION DE NUMEROS PARES DESCENDIENTES"; 
	DEFINIR X COMO ENTERO; 
	X<-60;
	MIENTRAS X > 0 HACER
		ESCRIBIR X;
		X<-X-2;
		
	FinMientras
	
	
FinProceso
