Proceso DIGITOS_DE_NUMERO
	//CREAR UN PROGRAMA QUE CALCULE CUANTAS CIFRAS TIENE UN NUMERO ENTERO POSITIVO
	
	DEFINIR N, CONT, AUX COMO REAL; 
	ESCRIBIR "INGRESE UN NUMERO ENTERO POSITIVO"; 
	LEER N;
	CONT<-0; 
	AUX<-N;
	MIENTRAS AUX >0 HACER 
		CONT<-CONT+1;
		AUX<-TRUNC(AUX/10); 
	FinMientras
	ESCRIBIR "EL NUMERO TIENE ", CONT , " DIGITOS";
	
FinProceso
