//CONVERSION DE MILLAS A KILOMETROS 

Algoritmo MILLAS_KILOMETROS
	DEFINIR MILLAS, KILOMETROS COMO REALES; 
	
	
	ESCRIBIR "INSERTE LA CANTIDAD DE MILLAS QUE QUIERE CONVERTIR"; 
	LEER MILLAS; 
	KILOMETROS<-MILLAS*1609; 
	ESCRIBIR "LOS KILOMETROS EQUIVALENTES SON: ", KILOMETROS; 
	
FinAlgoritmo
