//CALCULE LA SUMA: S=1*2+2*3+3*4+nx(n+1)

Proceso sin_titulo
	
	DEFINIR N, SUMA COMO ENTERO;
	ESCRIBIR "BIENVENIDO AL PROGRAMA DE CALCULO DE SUMA"; 
	ESCRIBIR "POR FAVOR INGRESE EN NUMERO QUE DESEE";
	LEER N;
	
	SUMA<-(1*2)+(2*3)+(3*4)+(N*N)+1;
	
	ESCRIBIR "EL RESULTADO DE LA OPERACION ES ", SUMA;
FinProceso
