//CALCULE LA SUMA S=1+3+5+7
//(2N-1)

Proceso CALCULO_SUMA
	
	DEFINIR N COMO REAL; 
	
	ESCRIBIR "BIENVENIDO AL CALCULO DE SUMAS ARITMERICAS"; 
	ESCRIBIR "POR FAVOR INGRESE EL NUMERO QUE DESEA CALCULAR"; 
	LEER N; 
	
	N<-N+2-1;
	
	ESCRIBIR "EL RESULTADO DE TU SUMA ES ", N ; 
	
	
	
FinProceso
