//ESCRIBA UN PROGRAMA QUE LEA UNA HORA Y DIGA CUANTAS HORAS, MINUTOS Y 
//SEGUNDOS EQUIVALE 

Proceso CALCULO_TIEMPO
	
	DEFINIR HORA, MINUTOS, SEG COMO REAL; 
	
	ESCRIBIR "BIENVENIDO AL PROGRAMA DE CALCULO DEL TIEMPO"; 
	ESCRIBIR "POR FAVOR INSERTE LAS HORAS QUE DESEA CONVERTIR"; 
	LEER HORA; 
	ESCRIBIR  HORA, " HORAS EQUIVALE A: ";
	MINUTOS <-HORA*60; 
	ESCRIBIR MINUTOS, " MINUTOS";
	SEG<-MINUTOS*60; 
	ESCRIBIR SEG, " SEGUNDOS"; 
	
FinProceso
