//CALCULE LA MEDIA ARITMETICA DE LOS N PRIMEROS NUMEROS ENTEROS POSITIVOS 
Proceso MEDIA_ARITMETICA
	
	DEFINIR I, N COMO ENTEROS; 
	DEFINIR ACUM, DATO, PROM COMO REALES; 
	
	ESCRIBIR "INGRESE LA CANTIDAD DE DATOS"; 
	LEER N; 
	
	ACUM<-0; 
	
	PARA I<-1 HASTA N HACER
		
		ESCRIBIR "INGRESE EL DATO ", I,":";
		LEER DATO; 
		ACUM<-ACUM+DATO; 
		
	FinPara
	
	PROM<-ACUM/N; 
	
	ESCRIBIR "EL PROMEDIO ES: ", PROM; 
	
	
	
FinProceso
