Proceso VALOR_ABSOLUTO
	
	DEFINIR A, ABSOLUTO COMO REALES; 
	
	ESCRIBIR "BIENVENIDO AL PROGRAMA DE VALOR ABSULUTO DE LOS NUMEROS"; 
	ESCRIBIR "POR FAVOR INGRESA UN NUMERO"; 
	LEER A;
	ABSOLUTO<-ABS(A); 
	
	ESCRIBIR "EL VALOR ABSOLUTO DE ", A , " ES: ", ABSOLUTO; 
	
	
FinProceso
